# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SWAGile
tagline:          'Stories about the Tech World'
description:      'Funny, Scary, Infomative Stories to help us all forge our way'
url:              https://swagile.com
baseurl:          /

author:
  name:           'Christopher Massie'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/massiecd
